version: '3.7'

services:
    db:
        image: postgres:11.2 
    web:
        build: .
        command: python /ILead/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/ILead
        ports:
            - 8000:8000
        depends_on:
            - db
